// Deal controller — creation, retrieval, stage progression, fines verification,
// document generation, and completion. All business logic (fees, state machine)
// lives in /services; this file only validates input, calls services, and shapes responses.

const { supabaseAdmin } = require('../config/supabase');
const feeCalculator = require('../services/feeCalculator');
const dealFlowEngine = require('../services/dealFlowEngine');
const finesVerification = require('../services/finesVerificationService');
const docGen = require('../services/documentGenerator');
const { STAGES } = require('../utils/dealStages');
const logger = require('../utils/logger');

const SAFEPAY_MIN_SALE_PRICE = 100000;

/**
 * Looks up an existing buyer account by phone number. The buyer must already
 * have a ClearDrive account (self-serve signup) before a seller can attach
 * them to a deal — we never create phantom user rows for people who haven't
 * signed up, since buyer_id is a hard FK and the buyer must complete their
 * own KYC/signing steps under their own login.
 * @returns {Promise<{buyerId: string|null, error: string|null}>}
 */
async function resolveBuyerId(buyerPhone) {
  if (!buyerPhone) return { buyerId: null, error: null };
  const { data: buyer } = await supabaseAdmin.from('users').select('id').eq('phone', buyerPhone).eq('role', 'buyer').maybeSingle();
  if (!buyer) return { buyerId: null, error: 'No buyer account found with that phone number — ask the buyer to sign up first, then try again' };
  return { buyerId: buyer.id, error: null };
}

/**
 * Same pattern as resolveBuyerId, for dealers/brokers referring a seller they
 * don't have an account ID for — the seller must already have a ClearDrive account.
 */
async function resolveSellerId(sellerPhone) {
  if (!sellerPhone) return { sellerId: null, error: null };
  const { data: seller } = await supabaseAdmin.from('users').select('id').eq('phone', sellerPhone).eq('role', 'seller').maybeSingle();
  if (!seller) return { sellerId: null, error: 'No seller account found with that phone number — ask the seller to sign up first, then try again' };
  return { sellerId: seller.id, error: null };
}

/**
 * Dealers/brokers referring a deal are always credited as themselves — the
 * referral partner is never taken from client input for those roles, to
 * prevent one partner claiming another's referral fee. Linked by phone (see
 * partnerController.findMyPartner / authController.signup).
 */
async function resolveOwnPartnerId(appUser) {
  if (appUser.role !== 'dealer' && appUser.role !== 'broker') return null;
  const { data: partner } = await supabaseAdmin.from('partners').select('id').eq('phone', appUser.phone).eq('type', appUser.role).maybeSingle();
  return partner?.id || null;
}

/**
 * POST /api/deals — creates a new deal (quote stage) and calculates the
 * estimated net proceeds. Deal ref (CD-YYYY-NNN) is auto-generated by the DB.
 */
async function createDeal(req, res) {
  const {
    product, // 'loanclear' | 'safepay'
    plate,
    salePrice,
    loanAmount,
    loanBank,
    buyerPhone,
    sellerPhone,
    referralSource,
  } = req.body;

  // Sellers may only ever create deals for themselves — the sellerId is never
  // taken from client input for that role, to prevent one seller creating a
  // deal under another user's identity. Dealers/brokers referring a seller
  // they don't have an ID for may pass the seller's phone instead (the seller
  // must already have a ClearDrive account). Admins may pass an explicit sellerId.
  let sellerId = req.appUser.role === 'seller' ? req.appUser.id : req.body.sellerId;
  if (!sellerId && sellerPhone) {
    const { sellerId: resolved, error: sellerErr } = await resolveSellerId(sellerPhone);
    if (sellerErr) return res.status(400).json({ error: sellerErr });
    sellerId = resolved;
  }

  if (!['loanclear', 'safepay'].includes(product)) {
    return res.status(400).json({ error: 'product must be "loanclear" or "safepay"' });
  }
  if (!sellerId || !plate || typeof salePrice !== 'number' || salePrice <= 0) {
    return res.status(400).json({ error: 'sellerId (or sellerPhone), plate, and a positive salePrice are required' });
  }
  if (product === 'safepay' && salePrice < SAFEPAY_MIN_SALE_PRICE) {
    return res.status(400).json({ error: `SafePay requires a minimum sale price of AED ${SAFEPAY_MIN_SALE_PRICE.toLocaleString()}` });
  }
  if (product === 'loanclear' && (typeof loanAmount !== 'number' || loanAmount < 0)) {
    return res.status(400).json({ error: 'loanAmount (approximate) is required for LoanClear deals' });
  }

  const { buyerId, error: buyerErr } = await resolveBuyerId(buyerPhone);
  if (buyerErr) return res.status(400).json({ error: buyerErr });

  // Dealers/brokers are always credited as themselves; admins may still pass an
  // explicit referralPartnerId (e.g. entering a historical/offline referral).
  const referralPartnerId = req.appUser.role === 'admin' ? req.body.referralPartnerId : await resolveOwnPartnerId(req.appUser);

  const cdFee = product === 'loanclear' ? feeCalculator.calculateLoanClearFee(loanAmount) : feeCalculator.calculateSafePayFee(salePrice);
  const netProceeds = feeCalculator.calculateNetProceeds({ salePrice, loanAmount: product === 'loanclear' ? loanAmount : 0, finesAmount: 0, cdFee });

  let referralFee = null;
  if (referralPartnerId) {
    const { data: partner } = await supabaseAdmin.from('partners').select('*').eq('id', referralPartnerId).single();
    if (partner) {
      const dealValue = product === 'loanclear' ? loanAmount : salePrice;
      referralFee = feeCalculator.calculateReferralFee(dealValue, feeCalculator.isLoyaltyTier(partner.total_deals));
    }
  }

  const { data: deal, error } = await supabaseAdmin
    .from('deals')
    .insert({
      product,
      status: STAGES.QUOTE,
      seller_id: sellerId,
      buyer_id: buyerId,
      plate,
      sale_price: salePrice,
      loan_amount: product === 'loanclear' ? loanAmount : null,
      loan_bank: product === 'loanclear' ? loanBank : null,
      cd_fee: cdFee,
      net_proceeds: netProceeds,
      referral_source: (req.appUser.role === 'dealer' || req.appUser.role === 'broker') ? req.appUser.role : referralSource || 'direct',
      referral_partner_id: referralPartnerId || null,
      referral_fee: referralFee,
    })
    .select()
    .single();

  if (error) {
    logger.error('Failed to create deal', { error: error.message });
    return res.status(500).json({ error: 'Could not create deal — please try again' });
  }

  return res.status(201).json({ deal });
}

/**
 * PATCH /api/deals/:id/buyer — attaches (or replaces) the buyer on a deal by
 * phone number lookup. Used when the seller didn't have the buyer's details
 * at quote-creation time, and must be done before the deal reaches KYC so
 * the buyer's identity check can be sent to the right person.
 */
async function attachBuyer(req, res) {
  const { buyerPhone } = req.body;
  if (!buyerPhone) return res.status(400).json({ error: 'buyerPhone is required' });

  const { buyerId, error: buyerErr } = await resolveBuyerId(buyerPhone);
  if (buyerErr) return res.status(400).json({ error: buyerErr });

  const { data: updated, error } = await supabaseAdmin.from('deals').update({ buyer_id: buyerId }).eq('id', req.params.id).select().single();
  if (error || !updated) return res.status(404).json({ error: 'Deal not found' });

  return res.json({ deal: updated });
}

/**
 * GET /api/deals/mine — all deals where the calling user is the seller or
 * buyer, most recent first. Powers the seller/buyer "my deals" dashboards.
 */
async function listMine(req, res) {
  const userId = req.appUser.id;
  const { data: deals, error } = await supabaseAdmin
    .from('deals')
    .select('*')
    .or(`seller_id.eq.${userId},buyer_id.eq.${userId}`)
    .order('created_at', { ascending: false });

  if (error) return res.status(500).json({ error: 'Could not load your deals — please try again' });
  return res.json({ deals });
}

/** GET /api/deals/:id */
async function getDeal(req, res) {
  const { data: deal, error } = await supabaseAdmin.from('deals').select('*').eq('id', req.params.id).single();
  if (error || !deal) return res.status(404).json({ error: 'Deal not found' });
  return res.json({ deal });
}

/** PUT /api/deals/:id/stage — advances the deal to the next stage in the flow. */
async function advanceStage(req, res) {
  const { targetStage } = req.body;
  if (!targetStage) return res.status(400).json({ error: 'targetStage is required' });

  try {
    const updated = await dealFlowEngine.advanceStage(req.params.id, targetStage);
    return res.json({ deal: updated });
  } catch (err) {
    return res.status(400).json({ error: err.message });
  }
}

/**
 * POST /api/deals/:id/fines-verify — accepts a base64 RTA screenshot, runs
 * Claude Vision extraction, cross-validates against the deal's plate, and
 * (on success) marks the deal's fines as verified.
 */
async function verifyFines(req, res) {
  const { imageBase64, mediaType } = req.body;
  if (!imageBase64) return res.status(400).json({ error: 'imageBase64 is required' });

  const { data: deal, error } = await supabaseAdmin.from('deals').select('*').eq('id', req.params.id).single();
  if (error || !deal) return res.status(404).json({ error: 'Deal not found' });

  const result = await finesVerification.verifyFinesScreenshot({ imageBase64, mediaType, expectedPlate: deal.plate });

  if (!result.success) {
    return res.status(422).json({ verified: false, reason: result.reason });
  }

  const cdFee = deal.product === 'loanclear' ? feeCalculator.calculateLoanClearFee(deal.loan_amount) : feeCalculator.calculateSafePayFee(deal.sale_price);
  const netProceeds = feeCalculator.calculateNetProceeds({
    salePrice: deal.sale_price,
    loanAmount: deal.loan_amount || 0,
    finesAmount: result.finesAed,
    cdFee,
  });

  const { data: updated, error: updateErr } = await supabaseAdmin
    .from('deals')
    .update({ fines_amount: result.finesAed, fines_verified: true, cd_fee: cdFee, net_proceeds: netProceeds })
    .eq('id', deal.id)
    .select()
    .single();

  if (updateErr) return res.status(500).json({ error: 'Could not save verified fines — please try again' });

  return res.json({ verified: true, deal: updated });
}

/**
 * POST /api/deals/:id/generate-docs — manually (re)triggers document
 * generation for a deal. Normally this fires automatically on entering the
 * SIGNING stage (see dealFlowEngine), but this endpoint allows admin/manual re-generation.
 */
async function generateDocs(req, res) {
  const { data: deal, error } = await supabaseAdmin.from('deals').select('*').eq('id', req.params.id).single();
  if (error || !deal) return res.status(404).json({ error: 'Deal not found' });

  const [{ data: seller }, { data: buyer }, { data: partner }] = await Promise.all([
    deal.seller_id ? supabaseAdmin.from('users').select('*').eq('id', deal.seller_id).single() : { data: null },
    deal.buyer_id ? supabaseAdmin.from('users').select('*').eq('id', deal.buyer_id).single() : { data: null },
    deal.referral_partner_id ? supabaseAdmin.from('partners').select('*').eq('id', deal.referral_partner_id).single() : { data: null },
  ]);

  const doc001 = await docGen.generateDoc001(deal, seller, buyer);
  const doc002 = await docGen.generateDoc002(deal, seller);
  const doc003 = partner ? await docGen.generateDoc003(deal, partner) : null;
  const doc009 = deal.trustin_escrow_iban ? await docGen.generateDoc009(deal) : null;

  const updates = { doc001_url: doc001, doc002_url: doc002 };
  if (doc003) updates.doc003_url = doc003;
  await supabaseAdmin.from('deals').update(updates).eq('id', deal.id);

  return res.json({ generated: { doc001, doc002, doc003, doc009 } });
}

/** GET /api/deals/:id/docs — returns current document generation/signing status. */
async function getDocs(req, res) {
  const { data: deal, error } = await supabaseAdmin
    .from('deals')
    .select('doc001_url, doc001_signed, doc002_url, doc002_signed, doc003_url, doc003_signed, transfer_cert_url')
    .eq('id', req.params.id)
    .single();

  if (error || !deal) return res.status(404).json({ error: 'Deal not found' });
  return res.json({ docs: deal });
}

/**
 * POST /api/deals/:id/complete — seller has uploaded the RTA transfer
 * certificate; validates it and advances the deal to COMPLETE (which
 * triggers proceeds release + referral payout via dealFlowEngine).
 */
async function completeDeal(req, res) {
  const { transferCertUrl } = req.body;
  if (!transferCertUrl) return res.status(400).json({ error: 'transferCertUrl is required' });

  const { error: updateErr } = await supabaseAdmin.from('deals').update({ transfer_cert_url: transferCertUrl }).eq('id', req.params.id);
  if (updateErr) return res.status(500).json({ error: 'Could not save transfer certificate — please try again' });

  try {
    const updated = await dealFlowEngine.advanceStage(req.params.id, STAGES.COMPLETE);
    return res.json({ deal: updated });
  } catch (err) {
    return res.status(400).json({ error: err.message });
  }
}

const DETAILS_ALLOWED_FIELDS = [
  'vin',
  'loan_account',
  'seller_iban',
  'seller_acc_name',
  'seller_proc_bank',
  'make',
  'model',
  'year',
  'colour',
  'emirate',
  'mileage',
  'sale_price',
];

/**
 * PATCH /api/deals/:id/details — stage 4 (Vehicle & Financial Details): seller
 * submits VIN (from Mulkiya), loan account, agreed sale price, proceeds IBAN,
 * etc. Recalculates the ClearDrive fee and net proceeds if sale_price changes.
 */
async function updateDetails(req, res) {
  const { data: deal, error } = await supabaseAdmin.from('deals').select('*').eq('id', req.params.id).single();
  if (error || !deal) return res.status(404).json({ error: 'Deal not found' });

  const updates = {};
  for (const field of DETAILS_ALLOWED_FIELDS) {
    if (req.body[field] !== undefined) updates[field] = req.body[field];
  }

  if (Object.keys(updates).length === 0) {
    return res.status(400).json({ error: `No valid fields provided. Allowed: ${DETAILS_ALLOWED_FIELDS.join(', ')}` });
  }

  const salePrice = updates.sale_price ?? deal.sale_price;
  const loanAmount = deal.loan_amount || 0;
  const finesAmount = deal.fines_amount || 0;
  const cdFee = deal.product === 'loanclear' ? feeCalculator.calculateLoanClearFee(loanAmount) : feeCalculator.calculateSafePayFee(salePrice);
  updates.cd_fee = cdFee;
  updates.net_proceeds = feeCalculator.calculateNetProceeds({ salePrice, loanAmount, finesAmount, cdFee });

  const { data: updated, error: updateErr } = await supabaseAdmin.from('deals').update(updates).eq('id', deal.id).select().single();
  if (updateErr) return res.status(500).json({ error: 'Could not save deal details — please try again' });

  return res.json({ deal: updated });
}

module.exports = { createDeal, attachBuyer, getDeal, listMine, advanceStage, verifyFines, generateDocs, getDocs, completeDeal, updateDetails };
